server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5430/demoDB
#    url: jdbc:postgresql://192.168.0.56:5432/demoDB # for test
    username: usr
    password: pwd
  flyway:
    enabled: true

logging:
  level:
    org.springframework.jdbc.core.JdbcTemplate: TRACE