server:
  port: 8081

spring:
  r2dbc:
    url: r2dbc:postgresql://192.168.0.56:5432/demoDB
    username: usr
    password: pwd
  flyway:
    url: jdbc:postgresql://192.168.0.56:5432/demoDB
    user: usr
    password: pwd


logging:
  level:
    org.springframework.jdbc.core.JdbcTemplate: TRACE
